class CfgPatches {
	class CAU_ExtendedChat_EmojiPack_Twemoji_Popular {
		name="CAU_ExtendedChat_EmojiPack_Twemoji_Popular";
		author="ConnorAU";
		url="https://github.com/ConnorAU/A3ExtendedChat";

		requiredVersion=0.01;
		requiredAddons[]={};
		units[]={};
		weapons[]={};
	};
};

class CfgEmoji {
    #include "data\+1.cpp"
    #include "data\-1.cpp"
    #include "data\100.cpp"
    #include "data\angel.cpp"
    #include "data\angry.cpp"
    #include "data\astonished.cpp"
    #include "data\balloon.cpp"
    #include "data\beer.cpp"
    #include "data\beers.cpp"
    #include "data\birthday.cpp"
    #include "data\bow.cpp"
    #include "data\broken_heart.cpp"
    #include "data\christmas_tree.cpp"
    #include "data\clap.cpp"
    #include "data\cold_sweat.cpp"
    #include "data\confetti_ball.cpp"
    #include "data\confused.cpp"
    #include "data\cookie.cpp"
    #include "data\cry.cpp"
    #include "data\disappointed_relieved.cpp"
    #include "data\dizzy_face.cpp"
    #include "data\eggplant.cpp"
    #include "data\exploding_head.cpp"
    #include "data\eyes.cpp"
    #include "data\face_palm.cpp"
    #include "data\face_vomiting.cpp"
    #include "data\face_with_raised_eyebrow.cpp"
    #include "data\face_with_symbols_on_mouth.cpp"
    #include "data\first_place_medal.cpp"
    #include "data\frowning.cpp"
    #include "data\gift.cpp"
    #include "data\grimacing.cpp"
    #include "data\hankey.cpp"
    #include "data\heart.cpp"
    #include "data\heart_eyes.cpp"
    #include "data\hushed.cpp"
    #include "data\jack_o_lantern.cpp"
    #include "data\joy.cpp"
    #include "data\laughing.cpp"
    #include "data\neutral_face.cpp"
    #include "data\ok_hand.cpp"
    #include "data\open_mouth.cpp"
    #include "data\partying_face.cpp"
    #include "data\peach.cpp"
    #include "data\point_down.cpp"
    #include "data\point_left.cpp"
    #include "data\point_right.cpp"
    #include "data\point_up.cpp"
    #include "data\popcorn.cpp"
    #include "data\rage.cpp"
    #include "data\raised_hand_with_fingers_splayed.cpp"
    #include "data\relieved.cpp"
    #include "data\rolling_on_the_floor_laughing.cpp"
    #include "data\salt.cpp"
    #include "data\scream.cpp"
    #include "data\second_place_medal.cpp"
    #include "data\shrug.cpp"
    #include "data\skull.cpp"
    #include "data\sleeping.cpp"
    #include "data\sleepy.cpp"
    #include "data\slightly_frowning_face.cpp"
    #include "data\slightly_smiling_face.cpp"
    #include "data\smile.cpp"
    #include "data\smiley.cpp"
    #include "data\smirk.cpp"
    #include "data\sob.cpp"
    #include "data\sparkles.cpp"
    #include "data\sunglasses.cpp"
    #include "data\sweat_drops.cpp"
    #include "data\sweat_smile.cpp"
    #include "data\tada.cpp"
    #include "data\teddy_bear.cpp"
    #include "data\thinking_face.cpp"
    #include "data\third_place_medal.cpp"
    #include "data\triumph.cpp"
    #include "data\trophy.cpp"
    #include "data\upside_down_face.cpp"
    #include "data\wave.cpp"
    #include "data\weary.cpp"
    #include "data\wink.cpp"
    #include "data\worried.cpp"
    #include "data\zzz.cpp"
};
